server.port=8081
spring.data.mongodb.uri=mongodb://mongo:ReRZBkUILVVxEdSbqcguUFDPzzzviWui@mongodb.railway.internal:27017/smart_market 
spring.data.mongodb.auto-index-creation=true

spring.application.name=USER-SERVICE
#eureka.client.service-url.defaultZone=http://localhost:8761

jwt.public.key=classpath:keys/public.pem
jwt.private.key=classpath:keys/private.pem

