server.port=8081
spring.data.mongodb.uri=mongodb+srv://ruchita7119:Ruchita@7119@cluster0.xfmgh.mongodb.net/?appName=Cluster0
spring.data.mongodb.auto-index-creation=true

spring.application.name=USER-SERVICE
#eureka.client.service-url.defaultZone=http://localhost:8761 

jwt.public.key=classpath:keys/public.pem
jwt.private.key=classpath:keys/private.pem

