server.port=8081
spring.data.mongodb.uri=mongodb://atlas-sql-674061709ab0275f05d921e5-xfmgh.a.query.mongodb.net/myVirtualDatabase?ssl=true&authSource=admin
spring.data.mongodb.auto-index-creation=true

spring.application.name=USER-SERVICE
#eureka.client.service-url.defaultZone=http://localhost:8761 

jwt.public.key=classpath:keys/public.pem
jwt.private.key=classpath:keys/private.pem

